/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 1 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {3.429349083840342, -1.343184807687476, -1.428052084689983, 3.986530261109070, -3.066572460598108, -38.906341379222638, 19.138574525483182, 19.676297208837397, -1.733975615870553, 0.678964178214780, -1.725713697575495, 0.681906014812818, -4.019295986363835, 4.617581575448066, -1.732573112999245, 0.693454896587292, 0.000000000000000, 0.000000000000000, 1.725713697575495, -0.681906014812818, 4.794612870823006, -3.106659030116808, -1.732573112999245, 0.693454896587292, 1.733975615870553, -0.678964178214780, 1.732573112999245, -0.693454896587292, -1.733975615870553, 0.678964178214780, -1.733975615870553, 0.678964178214780, -1.732573112999245, 0.693454896587292, -38.885251209610281, -58.314220631947542, -3.004021036241007, -48.315861619864670, -1.733975615870553, 0.678964178214780, 0.240317045483459, -0.229156197991094, 0.230103843376932, -0.697610311952519, 0.203432256317474, -0.601698522108422, -0.599920143665113, 3.590684805873924, -0.615179558528036, 0.700085615282941, -0.599920143665113, -0.926538661567802, -0.615179558528036, -0.601698522108422, -0.615179558528036, -0.601698522108422, -0.601698522108422, -0.615179558528036, 0.017210934102157, 1.302459557963453, -0.601698522108422};
	double * mw = mainWeights;
	double hiddenLayer1outputs[20];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.000000000000000) / 222.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = exp(-(hiddenLayer1outputs[0] * hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = exp(-(hiddenLayer1outputs[1] * hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = exp(-(hiddenLayer1outputs[2] * hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = exp(-(hiddenLayer1outputs[3] * hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = exp(-(hiddenLayer1outputs[4] * hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = exp(-(hiddenLayer1outputs[5] * hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = exp(-(hiddenLayer1outputs[6] * hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = exp(-(hiddenLayer1outputs[7] * hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = exp(-(hiddenLayer1outputs[8] * hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = exp(-(hiddenLayer1outputs[9] * hiddenLayer1outputs[9]));
	hiddenLayer1outputs[10] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[10] += *mw++ * inputs[c];
	hiddenLayer1outputs[10] = exp(-(hiddenLayer1outputs[10] * hiddenLayer1outputs[10]));
	hiddenLayer1outputs[11] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[11] += *mw++ * inputs[c];
	hiddenLayer1outputs[11] = exp(-(hiddenLayer1outputs[11] * hiddenLayer1outputs[11]));
	hiddenLayer1outputs[12] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[12] += *mw++ * inputs[c];
	hiddenLayer1outputs[12] = exp(-(hiddenLayer1outputs[12] * hiddenLayer1outputs[12]));
	hiddenLayer1outputs[13] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[13] += *mw++ * inputs[c];
	hiddenLayer1outputs[13] = exp(-(hiddenLayer1outputs[13] * hiddenLayer1outputs[13]));
	hiddenLayer1outputs[14] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[14] += *mw++ * inputs[c];
	hiddenLayer1outputs[14] = exp(-(hiddenLayer1outputs[14] * hiddenLayer1outputs[14]));
	hiddenLayer1outputs[15] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[15] += *mw++ * inputs[c];
	hiddenLayer1outputs[15] = exp(-(hiddenLayer1outputs[15] * hiddenLayer1outputs[15]));
	hiddenLayer1outputs[16] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[16] += *mw++ * inputs[c];
	hiddenLayer1outputs[16] = exp(-(hiddenLayer1outputs[16] * hiddenLayer1outputs[16]));
	hiddenLayer1outputs[17] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[17] += *mw++ * inputs[c];
	hiddenLayer1outputs[17] = exp(-(hiddenLayer1outputs[17] * hiddenLayer1outputs[17]));
	hiddenLayer1outputs[18] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[18] += *mw++ * inputs[c];
	hiddenLayer1outputs[18] = exp(-(hiddenLayer1outputs[18] * hiddenLayer1outputs[18]));
	hiddenLayer1outputs[19] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[19] += *mw++ * inputs[c];
	hiddenLayer1outputs[19] = exp(-(hiddenLayer1outputs[19] * hiddenLayer1outputs[19]));
	outputs[0] = *mw++;
	for(c = 0; c < 20; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = exp(-(outputs[0] * outputs[0]));
	outputs[0] = 30.399999999999999 + (outputs[0] - 0.000000) * 109.599999999999994;
}
