/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 1 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {0.305847053766654, 0.497407248488305, 0.721411285227695, -0.033168151527149, 0.470611047911906, 0.480449674489252, -0.585765635547349, -0.762927264792897, -0.431956351587510, 0.057648819176163, 0.332551626932974, -0.754875094937541, -0.330877443914748, -0.492045991480741, 0.925507583366280, 1.244056423885007, 0.189464746652844, -0.498093879059615, 0.830881464212361, -0.096158721432439, -0.164652463907336, 0.588830099580395, -1.122644381405215, -1.577378226896522, -0.544063004956211, -0.774698196195284, 0.874784832331424, 1.188449922818744, -0.779478922081644, 0.068509248462053, 0.242952890822678, 1.011662702565550, -0.669473436595682, -0.028960348918565, 8.489197859599983, 6.712094719101419, 8.230366841487241, 10.348691111203642, -0.670414991736685, -0.809882965322856, -0.645585547059342, 0.583538577583797, -0.080437155065207, 0.262508052763069, -1.708881960274073, 0.263173676234468, -0.657169304581974, -0.845785806412282, 0.902829051240374, -0.095989386836156, -0.094209425305967, 0.978096672596254, -1.955559313362320, -0.449489072079635, 0.760482418156691, 0.589371710596020, -12.672074051273412, -0.263973316062090, 14.000244822692295, -1.662995061942511, -12.258020491156024};
	double * mw = mainWeights;
	double hiddenLayer1outputs[20];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.000000000000000) / 222.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[9]));
	hiddenLayer1outputs[10] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[10] += *mw++ * inputs[c];
	hiddenLayer1outputs[10] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[10]));
	hiddenLayer1outputs[11] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[11] += *mw++ * inputs[c];
	hiddenLayer1outputs[11] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[11]));
	hiddenLayer1outputs[12] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[12] += *mw++ * inputs[c];
	hiddenLayer1outputs[12] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[12]));
	hiddenLayer1outputs[13] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[13] += *mw++ * inputs[c];
	hiddenLayer1outputs[13] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[13]));
	hiddenLayer1outputs[14] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[14] += *mw++ * inputs[c];
	hiddenLayer1outputs[14] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[14]));
	hiddenLayer1outputs[15] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[15] += *mw++ * inputs[c];
	hiddenLayer1outputs[15] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[15]));
	hiddenLayer1outputs[16] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[16] += *mw++ * inputs[c];
	hiddenLayer1outputs[16] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[16]));
	hiddenLayer1outputs[17] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[17] += *mw++ * inputs[c];
	hiddenLayer1outputs[17] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[17]));
	hiddenLayer1outputs[18] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[18] += *mw++ * inputs[c];
	hiddenLayer1outputs[18] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[18]));
	hiddenLayer1outputs[19] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[19] += *mw++ * inputs[c];
	hiddenLayer1outputs[19] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[19]));
	outputs[0] = *mw++;
	for(c = 0; c < 20; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = 1.0 / (1.0 + exp(-outputs[0]));
	outputs[0] = 30.399999999999999 + (outputs[0] - 0.000000) * 109.599999999999994;
}
