/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 4 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {-23.232400426200225, -14.040475836839715, -1.487833850119138, 7.534354305232348, 7.557795415136310, 4.153320854668987, 14.285267229939372, -2.397918938831944, -4.012667056953293, 3.867288112801611, -10.092634714684591, 5.979572703590052, -8.451003949745301, -15.392010597028420, 3.477455829314679, 1.214848700315425, 16.232037991819922, -0.661392664063619, 9.604085733744419, -4.652582791241638, -23.122996021237398, -29.406139558357570, -0.248069449540781, -1.679199639416570, -6.491632104024717, -2.108292120970159, 21.071811695995265, 10.615776656193622, -9.436165133954839, 13.318369824734241, -5.587697659468160, -13.207579998002654, 1.770213367082641, -8.863445873821664, 0.444300887516765, -15.471546042687619, -19.574915960407381, 2.874229191354550, -3.778247731253378, -4.151785001096973, -2.816449263275860, 1.476786748237106, -6.836435339884981, 0.535129218184579, 3.931510245678209, -1.329363577172351, 5.269482561776941, -3.837159430769408, -4.866905085342474, 5.033125923184765, -0.766433640278446, -1.502561957773578, 0.778026312684685, 0.771565499010840, 0.654247826981103, -1.463438012621352, 1.778018012251536, 0.546695312933152, 1.113421227384927, 0.974330454450733, -1.646398438687704};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 4.400000000000000) / 170.300000000000011;
	inputs[1] = -1.0 + (inputs[1] - 0.200000000000000) / 1.650000000000000;
	inputs[2] = -1.0 + (inputs[2] - 6.500000000000000) / 0.450000000000000;
	inputs[3] = -1.0 + (inputs[3] - 4.300000000000000) / 1.300000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[9]));
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = 1.0 / (1.0 + exp(-outputs[0]));
	outputs[0] = 29.199999999999999 + (outputs[0] - 0.000000) * 98.500000000000000;
}
