/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 4 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {-0.222874897396925, 7.146973993449279, -0.563126588236458, -0.741499978189304, 0.703015673697080, -16.243788810013960, 7.046481999919056, -11.247565647104999, 12.015779241418251, -3.529606045810131, -4.219791822723258, 0.357458303513836, -2.859205333530195, -7.274172812128156, 2.960846192255526, -4.720248517485066, -6.184019960276107, -3.130350630918931, 8.087059621796804, 2.741090452971351, -2.107490235979292, 2.159625557161572, -5.084056932489986, -8.845203751167618, 5.784384351887958, -0.798031964785516, 3.944487518976064, 3.248244466505312, 2.506528451691624, -0.353186411834355, 0.943121571342876, -0.526867432852246, 1.950957808282007, 0.265940377357642, -1.715678767515177, 6.559739951534580, 4.372260850014447, -0.310538569520332, -1.658209962506316, -2.226407959245369, -12.370415728280314, -15.745724686800409, 4.967353076431923, 10.753527026667241, -8.108130946963373, -3.812685039911801, 3.846164810874730, -0.383355080684282, -2.139097910451779, 4.818163213401108, -0.896120187604053, 0.244514258937053, 0.241357712377894, -0.263208066414480, -0.159014336746518, -0.098776890400799, 0.232210436785225, 0.229324889183105, -0.418525533808597, -0.148222042696929, 0.574397774672498};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 4.000000000000000) / 170.500000000000000;
	inputs[1] = -1.0 + (inputs[1] - 0.200000000000000) / 1.650000000000000;
	inputs[2] = -1.0 + (inputs[2] - 6.500000000000000) / 0.500000000000000;
	inputs[3] = -1.0 + (inputs[3] - 4.300000000000000) / 1.350000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = exp(-(hiddenLayer1outputs[0] * hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = exp(-(hiddenLayer1outputs[1] * hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = exp(-(hiddenLayer1outputs[2] * hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = exp(-(hiddenLayer1outputs[3] * hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = exp(-(hiddenLayer1outputs[4] * hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = exp(-(hiddenLayer1outputs[5] * hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = exp(-(hiddenLayer1outputs[6] * hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = exp(-(hiddenLayer1outputs[7] * hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = exp(-(hiddenLayer1outputs[8] * hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = exp(-(hiddenLayer1outputs[9] * hiddenLayer1outputs[9]));
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = exp(-(outputs[0] * outputs[0]));
	outputs[0] = 29.199999999999999 + (outputs[0] - 0.000000) * 98.500000000000000;
}
