/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 1 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {-3.284750669655925, 2.090490083520596, -3.323780040719981, 2.125256098024536, -3.457666764905461, 2.119200664134063, 57.529557749663148, 61.047437590393820, -7.196236067404711, 6.920463276714662, -3.256347570782475, 2.128091543680767, -6.843636928819453, 6.654900928551667, -12.378605235227152, -8.009528474718245, -3.398960347585588, 2.113149845338649, -6.478978465926777, 6.261042006071999, -3.424425613248823, 2.090018733464146, -3.425572144161039, 2.133177249380652, -3.256732981106625, 2.128077619503654, -6.047124599645167, 13.219870918135287, -3.256207406169208, 2.128096608713073, -0.680590615927858, 22.681186630481669, -6.578425782431916, 6.336673412256483, -6.291976407115549, 6.055324217716198, -3.392169033366344, 2.115404844780115, -3.348507407101041, 2.110921624503406, -1.156106026787019, 3.584781651258130, 3.537579735915110, 3.662182968694829, 0.633179062543097, -4.604199951799740, 3.626562388581671, -4.187210425333488, -4.800462519414595, 3.648118346996573, -2.600208494655447, 3.616841650396394, 3.613659738306890, 3.627888217910926, -0.936225263911454, 3.626080334325045, -0.634783777280792, -2.872950489418101, -2.172352326956466, 3.632159481849948, 3.632095758650193};
	double * mw = mainWeights;
	double hiddenLayer1outputs[20];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.000000000000000) / 222.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[9]));
	hiddenLayer1outputs[10] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[10] += *mw++ * inputs[c];
	hiddenLayer1outputs[10] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[10]));
	hiddenLayer1outputs[11] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[11] += *mw++ * inputs[c];
	hiddenLayer1outputs[11] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[11]));
	hiddenLayer1outputs[12] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[12] += *mw++ * inputs[c];
	hiddenLayer1outputs[12] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[12]));
	hiddenLayer1outputs[13] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[13] += *mw++ * inputs[c];
	hiddenLayer1outputs[13] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[13]));
	hiddenLayer1outputs[14] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[14] += *mw++ * inputs[c];
	hiddenLayer1outputs[14] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[14]));
	hiddenLayer1outputs[15] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[15] += *mw++ * inputs[c];
	hiddenLayer1outputs[15] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[15]));
	hiddenLayer1outputs[16] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[16] += *mw++ * inputs[c];
	hiddenLayer1outputs[16] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[16]));
	hiddenLayer1outputs[17] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[17] += *mw++ * inputs[c];
	hiddenLayer1outputs[17] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[17]));
	hiddenLayer1outputs[18] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[18] += *mw++ * inputs[c];
	hiddenLayer1outputs[18] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[18]));
	hiddenLayer1outputs[19] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[19] += *mw++ * inputs[c];
	hiddenLayer1outputs[19] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[19]));
	outputs[0] = *mw++;
	for(c = 0; c < 20; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = 1.0 / (1.0 + exp(-outputs[0]));
	outputs[0] = 30.399999999999999 + (outputs[0] - 0.000000) * 109.599999999999994;
}
