/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 4 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {-1.621992230415344, 0.930707931518555, -0.967394709587097, -1.007443785667419, -1.516441106796265, 0.285182297229767, -0.434152841567993, -0.033754926174879, -0.830363035202026, -0.722691833972931, 0.401148557662964, 0.472712486982346, -0.210509628057480, -0.792483448982239, -0.274722814559937, 0.245641812682152, 0.659884035587311, 0.306913346052170, 0.619536638259888, -0.091220825910568, -0.874418258666992, -1.064230680465698, -0.789899170398712, 0.521193265914917, -0.414990365505219, 0.052241485565901, -0.042634036391973, -0.489157676696777, 0.801336824893951, 0.891096413135529, 0.308785885572433, 0.289666295051575, -0.108959272503853, 0.569697678089142, -1.542107105255127, 0.211810648441315, -0.853997945785522, 0.569593369960785, -0.968152165412903, -0.422958016395569, -0.016057703644037, -0.843911409378052, 0.508710086345673, -0.437329530715942, -0.007977526634932, -1.021455168724060, 0.364748746156693, 0.129935652017593, -0.557601928710938, -0.948994934558868, 1.192377567291260, -1.934033036231995, 0.211710318922997, -0.182189688086510, 0.690550744533539, -1.065165758132935, 1.207229495048523, -1.360475897789001, -0.937499642372131, -0.045523464679718, -0.337682127952576};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.300000000000000) / 221.849999999999994;
	inputs[1] = -1.0 + (inputs[1] - 30.399999999999999) / 49.000000000000000;
	inputs[2] = -1.0 + (inputs[2] - 30.399999999999999) / 49.000000000000000;
	inputs[3] = -1.0 + (inputs[3] - 30.399999999999999) / 49.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[9]));
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = 1.0 / (1.0 + exp(-outputs[0]));
	outputs[0] = 30.399999999999999 + (outputs[0] - 0.000000) * 98.000000000000000;
}
