/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 1 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {3.711172536543381, -1.411815531949949, -3.844659281588750, -2.111276115873338, 1.609954679184250, -0.750591249013449, -1.609954679184250, 0.750591249013449, -2.038130901353033, 2.028011704367871, 4.818649176062386, -4.539972159116392, -1.609954679184250, 0.750591249013449, 1.609954679184250, -0.750591249013449, 0.000000000000000, 0.000000000000000, 25.564444494220893, 26.410775745046529, -0.134037793749274, 0.764772671982889, -2.036307759572720, 0.828796777169830, 0.828796777169830, -0.328004397378952, 0.734014708321882, 0.828796777169830, 0.828796777169830, -0.780954646394268, -0.133412545129600};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.000000000000000) / 222.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = exp(-(hiddenLayer1outputs[0] * hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = exp(-(hiddenLayer1outputs[1] * hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = exp(-(hiddenLayer1outputs[2] * hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = exp(-(hiddenLayer1outputs[3] * hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = exp(-(hiddenLayer1outputs[4] * hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = exp(-(hiddenLayer1outputs[5] * hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = exp(-(hiddenLayer1outputs[6] * hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = exp(-(hiddenLayer1outputs[7] * hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = exp(-(hiddenLayer1outputs[8] * hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = exp(-(hiddenLayer1outputs[9] * hiddenLayer1outputs[9]));
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = exp(-(outputs[0] * outputs[0]));
	outputs[0] = 30.399999999999999 + (outputs[0] - 0.000000) * 109.599999999999994;
}
