/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 4 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {1.363149909455557, 0.865922938232559, 0.072363217490292, 0.288051103070231, -1.163818390675569, 4.754730231412652, -23.614066434430754, 11.075568449399000, 6.831719514971943, -23.252210498295220, 3.205478813099792, -6.226068148180679, -0.853662493781059, 8.510466735571255, -20.745881236261507, -4.598334593057758, -1.821613170360590, -5.342263843623141, -1.127224950096475, 7.120392870225323, -1.777405951263794, 0.722646492465287, -1.705410273603507, 9.570136041444831, -0.005445082546127, 5.484754195933272, 8.208329282110666, 0.125663910501322, -3.395867468987781, 4.773029358866672, 16.725137703268345, -21.461303998553042, -8.081004223984849, 5.903616109497086, 23.079328289816981, 35.774109028980739, 9.506495655877526, 9.308847074438498, 18.648653643392905, -49.221309395944431, 5.842931772906815, 11.068845157016149, -4.481246184107190, -2.498391928888927, -2.625732234150156, 1.994645369956084, -0.486651761000841, 4.386019362234714, -0.094977622690183, -3.046159688305700, -0.486479650946078, 0.632259608079726, 0.100954541283085, -0.183194904057467, -0.220059744115885, 0.074353303033310, 0.111968011456872, -0.182913468266883, 0.311522169719496, -0.090709521272338, -0.326811631270418};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 4.400000000000000) / 170.300000000000011;
	inputs[1] = -1.0 + (inputs[1] - 0.200000000000000) / 1.650000000000000;
	inputs[2] = -1.0 + (inputs[2] - 6.500000000000000) / 0.450000000000000;
	inputs[3] = -1.0 + (inputs[3] - 4.300000000000000) / 1.300000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = tanh(hiddenLayer1outputs[0]);
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = tanh(hiddenLayer1outputs[1]);
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = tanh(hiddenLayer1outputs[2]);
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = tanh(hiddenLayer1outputs[3]);
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = tanh(hiddenLayer1outputs[4]);
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = tanh(hiddenLayer1outputs[5]);
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = tanh(hiddenLayer1outputs[6]);
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = tanh(hiddenLayer1outputs[7]);
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = tanh(hiddenLayer1outputs[8]);
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = tanh(hiddenLayer1outputs[9]);
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = tanh(outputs[0]);
	outputs[0] = 29.199999999999999 + (outputs[0] - -1.000000) * 49.250000000000000;
}
