/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 3 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {0.201255634427071, -1.544366359710693, 0.972505986690521, -0.253691405057907, -5.652687549591064, -1.238923549652100, -1.081403493881226, -3.802675247192383, 2.122459411621094, -0.615869104862213, -0.309503823518753, 0.504666268825531, -0.626186847686768, -0.412553638219833, -0.638887286186218, 0.342638432979584, 1.168198585510254, 0.019512817263603, -0.965842127799988, -0.907733082771301, 1.432647347450256, -0.827378869056702, 0.150590345263481, -1.558303833007813, -0.856356441974640, -0.953874409198761, 1.549078345298767, 1.707213878631592, -0.093975417315960, 0.186675861477852, -0.683823168277740, 0.272757411003113, -1.029773116111755, 0.235573723912239, 0.254779815673828, 0.665727913379669, 0.822816431522369, -0.082628279924393, -0.721306741237640, -0.354236394166946, -0.270182490348816, -1.066010594367981, -3.525598049163818, 1.766059160232544, -0.294035583734512, -0.615660667419434, -1.628625869750977, 1.659811019897461, 1.560504078865051, 0.787560701370239, -0.168662801384926};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.300000000000000) / 221.849999999999994;
	inputs[1] = -1.0 + (inputs[1] - 30.399999999999999) / 49.000000000000000;
	inputs[2] = -1.0 + (inputs[2] - 30.399999999999999) / 49.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[9]));
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = 1.0 / (1.0 + exp(-outputs[0]));
	outputs[0] = 30.399999999999999 + (outputs[0] - 0.000000) * 98.000000000000000;
}
