/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 4 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {60.151917751939607, 22.764996888009275, 7.866843822896331, -12.629382357601170, -43.017552848168165, 2.289179823479771, 11.731116049770444, 6.365155623503211, -24.846374133514903, 38.302406819631514, -1.256408179108474, 34.883754423151039, -14.669032904650601, 2.158113994239390, -0.263909266651906, -4.519201475116111, -10.521812459251850, 3.592902315388993, 17.918573427635966, 0.538440241757446, 0.163506689234730, 1.784751377962786, -1.699562850627363, -14.732018980825979, 0.823024665824336, -4.873513924885613, -1.028793363106310, -7.308310006905452, 5.433979180124958, 8.805979958703603, 0.335061768085220, 5.586503040655785, -4.650870101965469, -35.536579142358015, 10.523165313158048, -0.000000000005494, -0.000000000006098, -0.000000000010512, -0.000000000001344, -0.000000000010341, 1.099628537779304, 0.056860290997205, 3.209883265186007, 1.206201997505741, -4.999501488447740, 1.128853423200522, 0.898155057928036, 1.473824671013199, 0.589209250231519, -3.000423805729273, -0.326918356727296, 0.412558780523818, 0.093451937290801, 0.080926515875221, 0.163920640270500, 0.348040114628029, 0.224042653133980, -0.199914472203288, -0.000000000000181, -0.431541901169990, 0.688708463842975};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 4.000000000000000) / 170.500000000000000;
	inputs[1] = -1.0 + (inputs[1] - 0.200000000000000) / 1.650000000000000;
	inputs[2] = -1.0 + (inputs[2] - 6.500000000000000) / 0.500000000000000;
	inputs[3] = -1.0 + (inputs[3] - 4.300000000000000) / 1.350000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = tanh(hiddenLayer1outputs[0]);
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = tanh(hiddenLayer1outputs[1]);
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = tanh(hiddenLayer1outputs[2]);
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = tanh(hiddenLayer1outputs[3]);
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = tanh(hiddenLayer1outputs[4]);
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = tanh(hiddenLayer1outputs[5]);
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = tanh(hiddenLayer1outputs[6]);
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = tanh(hiddenLayer1outputs[7]);
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = tanh(hiddenLayer1outputs[8]);
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = tanh(hiddenLayer1outputs[9]);
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = tanh(outputs[0]);
	outputs[0] = 29.199999999999999 + (outputs[0] - -1.000000) * 49.250000000000000;
}
