/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 4 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {7.699131464189863, -4.567427331514904, 4.630219284925166, 3.443876473850444, -4.234447164861363, 0.933241612481412, 0.748121151122041, -0.265789582935137, 1.625432195887651, 0.585226376142194, -0.197289397175926, -0.261771032971000, 2.086844689252470, 0.665713182213647, -1.782472410245731, -0.195044949807675, 9.511312346212662, 6.140417536674171, -6.905074039581870, 0.162857175276018, 2.899343285094918, 1.170402063627901, -1.199513232334301, 6.342212790795026, -7.672488900349582, -0.023974198612931, -0.395937107473878, -1.287431651837180, -0.821331265138470, 1.483568602666547, 1.192091159024475, -3.486180601916740, 2.456458296069642, 0.860730726035108, 0.613031363997206, -2.304188313698401, 4.654979916696331, 5.234591332066720, -5.022786334291863, 3.141892425105929, 8.252086354892674, 10.934265278835296, 1.302066118537224, 3.247171880384019, 0.357422562119822, -6.879857582035900, -3.948937199701636, -0.653299602316252, 1.139029896291234, 1.916160482011300, -0.881011627936325, 1.810659145623148, -0.203560380928309, -0.272376273871306, 0.384637974490639, 0.063122422591501, 0.353746872219498, 0.179668847643146, 0.355458953907010, 0.132377457968681, -0.582099921465457};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 4.400000000000000) / 170.300000000000011;
	inputs[1] = -1.0 + (inputs[1] - 0.200000000000000) / 1.650000000000000;
	inputs[2] = -1.0 + (inputs[2] - 6.500000000000000) / 0.450000000000000;
	inputs[3] = -1.0 + (inputs[3] - 4.300000000000000) / 1.300000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = exp(-(hiddenLayer1outputs[0] * hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = exp(-(hiddenLayer1outputs[1] * hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = exp(-(hiddenLayer1outputs[2] * hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = exp(-(hiddenLayer1outputs[3] * hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = exp(-(hiddenLayer1outputs[4] * hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = exp(-(hiddenLayer1outputs[5] * hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = exp(-(hiddenLayer1outputs[6] * hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = exp(-(hiddenLayer1outputs[7] * hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = exp(-(hiddenLayer1outputs[8] * hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = exp(-(hiddenLayer1outputs[9] * hiddenLayer1outputs[9]));
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = exp(-(outputs[0] * outputs[0]));
	outputs[0] = 29.199999999999999 + (outputs[0] - 0.000000) * 98.500000000000000;
}
