/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 4 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {-0.546136181863136, 0.679288605930377, -0.053422896256284, -0.022102099518192, -0.098239238537434};
	double * mw = mainWeights;
	int c;

	inputs[0] = -1.0 + (inputs[0] - 4.000000000000000) / 170.500000000000000;
	inputs[1] = -1.0 + (inputs[1] - 0.200000000000000) / 1.650000000000000;
	inputs[2] = -1.0 + (inputs[2] - 6.500000000000000) / 0.500000000000000;
	inputs[3] = -1.0 + (inputs[3] - 4.300000000000000) / 1.350000000000000;
	outputs[0] = *mw++;
	for(c = 0; c < 4; c++) outputs[0] += *mw++ * inputs[c];
	outputs[0] = exp(-(outputs[0] * outputs[0]));
	outputs[0] = 29.199999999999999 + (outputs[0] - 0.000000) * 98.500000000000000;
}
