/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 4 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {-1.181215167045593, 0.641665756702423, -1.028839349746704, -0.904198646545410, -0.521735250949860, -0.445585250854492, -0.019367851316929, 0.014910791069269, -0.926260471343994, -0.317818522453308, -0.535897135734558, 1.034467816352844, 0.052453074604273, 0.089783042669296, 0.261956900358200, 1.030672550201416, -0.241986826062202, -0.650305390357971, -0.620853304862976, -0.199674397706985, 1.212455272674561, 0.037976395338774, 0.438121527433395, -0.153293326497078, 1.464864015579224, 0.709119141101837, -0.399115204811096, 0.584657013416290, 0.549220442771912, -0.980159521102905, 0.592327833175659, -0.586430072784424, 0.504751682281494, -0.292931258678436, 1.430928349494934, 0.605877816677094, -0.886130571365356, 0.231736734509468, -0.052081715315580, -0.621621668338776, -0.878186941146851, -0.807511806488037, 0.598524153232574, -0.127309828996658, -0.225715667009354, -0.851289391517639, 0.019614838063717, 0.011497805826366, -0.243439048528671, -0.271843314170837, -0.368727296590805, -1.335995793342590, -1.334732174873352, 0.840369462966919, 0.025966553017497, 2.069467544555664, -0.778766632080078, 1.054547190666199, -0.894711613655090, -0.104166254401207, -0.393528193235397};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.300000000000000) / 221.849999999999994;
	inputs[1] = -1.0 + (inputs[1] - 30.399999999999999) / 49.000000000000000;
	inputs[2] = -1.0 + (inputs[2] - 30.399999999999999) / 49.000000000000000;
	inputs[3] = -1.0 + (inputs[3] - 30.399999999999999) / 49.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 4; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[9]));
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = 1.0 / (1.0 + exp(-outputs[0]));
	outputs[0] = 30.399999999999999 + (outputs[0] - 0.000000) * 98.000000000000000;
}
