/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 1 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void code(double * inputs, double * outputs) {
	double mainWeights[] = {0.000000000000000, -0.000000000000000, 1.341764676700109, -0.530295230708711, 1.733444719944286, -0.358878040493344, -1.455575714801934, 0.251280586618362, 2.715615200164319, 0.904639195065198, -1.316946281316370, 0.401976652235813, -1.553294770224169, 16.177926334073220, -1.582714950120163, 0.079098523109805, 8.103724339810645, 6.716677835056199, 1.216532353257570, -0.548105775411953, -0.003417390464841, -1.816001612031235, 1.454663434834875, -0.442943617886456, -1.548364292319383, 0.096275819682036, -1.354759638049232, 0.446674911349874, -4.695179019824281, 3.826981148022119, -1.496259899052590, 0.178678908567869, 1.102792741324749, -0.553215586922503, 1.273952947679273, -0.429782051368982, -1.392100065974351, 0.291021136045330, -2.628692127138859, -3.328025122262300, -1.472055551568318, 0.386993912892313, 0.432119696343316, -0.511832321699359, 0.051091757005112, -2.652240838580135, 0.092575033726763, -0.125713643447121, -0.073852683027326, -1.795147046711762, 0.131467563796459, 0.180376179046704, 0.381490783579473, -0.028167198353649, 0.189150787612852, -1.380214343782394, -0.014933505194922, 0.300997858099809, 0.079807662868204, 0.088415367374578, 0.147956782986217};
	double * mw = mainWeights;
	double hiddenLayer1outputs[20];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.000000000000000) / 222.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = exp(-(hiddenLayer1outputs[0] * hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = exp(-(hiddenLayer1outputs[1] * hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = exp(-(hiddenLayer1outputs[2] * hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = exp(-(hiddenLayer1outputs[3] * hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = exp(-(hiddenLayer1outputs[4] * hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = exp(-(hiddenLayer1outputs[5] * hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = exp(-(hiddenLayer1outputs[6] * hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = exp(-(hiddenLayer1outputs[7] * hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = exp(-(hiddenLayer1outputs[8] * hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = exp(-(hiddenLayer1outputs[9] * hiddenLayer1outputs[9]));
	hiddenLayer1outputs[10] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[10] += *mw++ * inputs[c];
	hiddenLayer1outputs[10] = exp(-(hiddenLayer1outputs[10] * hiddenLayer1outputs[10]));
	hiddenLayer1outputs[11] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[11] += *mw++ * inputs[c];
	hiddenLayer1outputs[11] = exp(-(hiddenLayer1outputs[11] * hiddenLayer1outputs[11]));
	hiddenLayer1outputs[12] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[12] += *mw++ * inputs[c];
	hiddenLayer1outputs[12] = exp(-(hiddenLayer1outputs[12] * hiddenLayer1outputs[12]));
	hiddenLayer1outputs[13] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[13] += *mw++ * inputs[c];
	hiddenLayer1outputs[13] = exp(-(hiddenLayer1outputs[13] * hiddenLayer1outputs[13]));
	hiddenLayer1outputs[14] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[14] += *mw++ * inputs[c];
	hiddenLayer1outputs[14] = exp(-(hiddenLayer1outputs[14] * hiddenLayer1outputs[14]));
	hiddenLayer1outputs[15] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[15] += *mw++ * inputs[c];
	hiddenLayer1outputs[15] = exp(-(hiddenLayer1outputs[15] * hiddenLayer1outputs[15]));
	hiddenLayer1outputs[16] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[16] += *mw++ * inputs[c];
	hiddenLayer1outputs[16] = exp(-(hiddenLayer1outputs[16] * hiddenLayer1outputs[16]));
	hiddenLayer1outputs[17] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[17] += *mw++ * inputs[c];
	hiddenLayer1outputs[17] = exp(-(hiddenLayer1outputs[17] * hiddenLayer1outputs[17]));
	hiddenLayer1outputs[18] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[18] += *mw++ * inputs[c];
	hiddenLayer1outputs[18] = exp(-(hiddenLayer1outputs[18] * hiddenLayer1outputs[18]));
	hiddenLayer1outputs[19] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[19] += *mw++ * inputs[c];
	hiddenLayer1outputs[19] = exp(-(hiddenLayer1outputs[19] * hiddenLayer1outputs[19]));
	outputs[0] = *mw++;
	for(c = 0; c < 20; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = exp(-(outputs[0] * outputs[0]));
	outputs[0] = 30.399999999999999 + (outputs[0] - 0.000000) * 109.599999999999994;
}
