/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 1 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void Codigo(double * inputs, double * outputs) {
	double mainWeights[] = {0.000000000000000, 0.000000000000000, -0.000000000000000, -0.000000000000000, 0.000000000000000, 0.000000000000000, 0.000000000000000, 0.000000000000000, 0.000000000000000, 0.000000000000000, 21.066345974114331, 25.200732631044627, -0.000000000000000, -0.000000000000000, -0.568636600556274, -3.735910232741819, -0.000000000000000, -0.000000000000000, 0.000000000000000, 0.000000000000000, -0.168243108835127, 0.000000000000000, -0.000000000000000, 0.000000000000000, 0.000000000000000, 0.000000000000000, 0.384757472157654, -0.000000000000000, -0.279969151975545, -0.000000000000000, 0.000000000000000};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 4.000000000000000) / 170.500000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = tanh(hiddenLayer1outputs[0]);
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = tanh(hiddenLayer1outputs[1]);
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = tanh(hiddenLayer1outputs[2]);
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = tanh(hiddenLayer1outputs[3]);
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = tanh(hiddenLayer1outputs[4]);
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = tanh(hiddenLayer1outputs[5]);
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = tanh(hiddenLayer1outputs[6]);
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = tanh(hiddenLayer1outputs[7]);
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = tanh(hiddenLayer1outputs[8]);
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 1; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = tanh(hiddenLayer1outputs[9]);
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = tanh(outputs[0]);
	outputs[0] = 29.199999999999999 + (outputs[0] - -1.000000) * 49.250000000000000;
}
